### ISSUE TITLE
Installing into VirtualENV results in File Not Found error

### ISSUE THREAD

**Issue by mark0978** [japrogramer/django-uuid-contour#1]
```
(.project)mark@ender:~/Python/project$ pip install django-uuid-contour
Downloading/unpacking django-uuid-contour
  Downloading django-uuid-contour-0.2.1.tar.gz
  Running setup.py (path:/home/mark/Python/project/.project/build/django-uuid-contour/setup.py) egg_info for package django-uuid-contour
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/mark/Python/project/.project/build/django-uuid-contour/setup.py", line 22, in <module>
        long_description=read('README.md'),
      File "/home/mark/Python/project/.project/build/django-uuid-contour/setup.py", line 6, in read
        return open(os.path.join(CURRENT_DIR, fname)).read()
    IOError: [Errno 2] No such file or directory: '/home/mark/Python/project/.project/build/django-uuid-contour/README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/mark/Python/project/.project/build/django-uuid-contour/setup.py", line 22, in <module>

    long_description=read('README.md'),

  File "/home/mark/Python/project/.project/build/django-uuid-contour/setup.py", line 6, in read

    return open(os.path.join(CURRENT_DIR, fname)).read()

IOError: [Errno 2] No such file or directory: '/home/mark/Python/project/.project/build/django-uuid-contour/README.md'
```

**Comment by mark0978** [comment]
`pip install -e git+...` does not exhibit this issue

**Comment by mark0978** [comment]
Just noticed that python 3 is a requirement for this package.  This issue may not exist in a python 3 environment...  My environment was 2.7

**Comment by japrogramer** [comment]
Im really sorry for the late response, i hope the problem was solve with a py 3 environment. on the plus side, django now includes uuid fields.
